name: Build github cache
on:
  push:
    branches:
      - master
  workflow_dispatch:

## Cancel any multiple runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-github-cache:
    if: github.repository == 'erlang/erlang-org'
    runs-on: ubuntu-24.04
    steps:
      - name: Fetch ImageOS
        id: image-os
        run: echo "ImageOS=${ImageOS}" >> $GITHUB_OUTPUT

      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v4

      - name: asdf setup
        uses: asdf-vm/actions/setup@v3
        with:
          asdf_branch: v0.15.0
      - name: asdf add plugins
        uses: asdf-vm/actions/plugins-add@v3
      - name: asdf cache
        uses: actions/cache@v4
        with:
          path: ~/.asdf/installs
          key: ${{ steps.image-os.outcome.ImageOS }}-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ steps.image-os.outcome.ImageOS }}-asdf-
      - name: asdf install
        run: asdf install && asdf install erlang 26.2.5.9 && asdf reshim

      - name: Install tools
        run: sudo apt-get install -y xsltproc

      - name: Install rebar3
        run: sudo bash -c "curl https://s3.amazonaws.com/rebar3-nightly/rebar3 > /usr/local/bin/rebar3 && chmod +x /usr/local/bin/rebar3"

      - name: Fetch otp_versions.table
        run: make otp_versions.table

      - name: Build documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make build-docs

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          single-commit: true

      - name: Build _patches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # We run the un-cached command here as some artifacts may have been uploaded
        # to github since last time and the cache sha does not catch that
        run: make patches

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: _patches # The branch the action should deploy to.
          folder: _patches # The folder the action should deploy.
          single-commit: true

      - name: Build faq
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make faq

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: faq # The branch the action should deploy to.
          folder: faq # The folder the action should deploy.
          single-commit: true
      - name: Build _eeps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make _eeps

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: _eeps # The branch the action should deploy to.
          folder: _eeps # The folder the action should deploy.
          single-commit: true

      - name: Trigger netlify build
        env:
          NETLIFY_BUILD_TRIGGER: ${{ secrets.NETLIFY_BUILD_TRIGGER }}
        run: curl -X POST -d {} "${NETLIFY_BUILD_TRIGGER}"
